homepage:
    pattern:  /
    defaults: { _controller: HolloPostfixBundle:Default:index }

new:
    pattern:  /new
    defaults: { _controller: HolloPostfixBundle:Default:new }

update:
    pattern:  /update/{id}
    defaults: { _controller: HolloPostfixBundle:Default:update }

delete:
    pattern:  /delete/{id}
    defaults: { _controller: HolloPostfixBundle:Default:delete }

stat:
    pattern:  /stat
    defaults: { _controller: HolloPostfixBundle:Stat:index }
