<?php

namespace ITG\PostfixBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends EntityRepository
{
}